/******************************************************************************
 * map_node.h
 *
 * Author:      Matt Richard
 * Date:        Nov 19, 2011
 * Description: This ROS node receives the map generated by gmapping.
 *****************************************************************************/

#ifndef CONTROL_PANEL_MAP_NODE_H
#define CONTROL_PANEL_MAP_NODE_H

#include <QObject>
#include <QImage>
#include <QRgb>
#include "ros/ros.h"
#include "nav_msgs/OccupancyGrid.h"
#include <string>
#include "control_panel/globals.h"

/**
 * \class  MapNode
 * \author Matt Richard
 * \brief
 */
class MapNode : public QObject
{
	Q_OBJECT

	public:
		MapNode(ros::NodeHandle *nh_ptr);
		void subscribe();
		void unsubscribe();
		void mapCallback(const nav_msgs::OccupancyGridConstPtr &msg);
		void setTopic(const std::string &topic);
		std::string getTopic() const;

	signals:
        void mapReceived(const QImage &buffer);

	private:
		std::string topic_name;
		ros::NodeHandle *nh;
		ros::Subscriber map_sub;

        QRgb white;
        QRgb black;
        QRgb grey;
};

#endif // CONTROL_PANEL_MAP_NODE_H
